Repository elastic/apm-k8s-attacher, pull requests merged in 2022-09, with the labels that each got.

#55 ci: enable release for tags
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/docker-package-push.sh
Labels: Team:Automation

#61 release: helm chart to the prod environment when a git tag release is created
  .ci/Jenkinsfile
Labels: Team:Automation, apm-k8s-attacher

#63 docs: add index file for new book
  docs/apm-mutating-webhook.asciidoc
  docs/index.asciidoc
Labels: apm-k8s-attacher
